const galleryGroups = [
  {
    title: 'All',
    isActive: true,
    items: [
      {
        title: "Classrooms",
        description: "Our well-equipped classrooms are designed to provide a nurturing and stimulating learning environment. Each classroom is thoughtfully arranged to inspire creativity, curiosity, and engagement.",
        infoItems: [
          'src/assets/images/gallery/Image.png',
          'src/assets/images/gallery/Image-1.png',
          'src/assets/images/gallery/Image-2.png',
          'src/assets/images/gallery/Image-3.png',
          'src/assets/images/gallery/Image.png',
          'src/assets/images/gallery/Image-1.png',
          'src/assets/images/gallery/Image-2.png',
          'src/assets/images/gallery/Image-3.png',
          'src/assets/images/gallery/Image.png',
          'src/assets/images/gallery/Image-1.png',
          'src/assets/images/gallery/Image-2.png',
          'src/assets/images/gallery/Image-3.png',

        ],
      },
      {
        title: "Library",
        description: "Our expansive library is a treasure trove of books, fostering a love for reading and supporting students' literacy development.",
        infoItems: [
          'src/assets/images/gallery/Image-4.png',
          'src/assets/images/gallery/Image-5.png',
          'src/assets/images/gallery/Image-6.png',
          'src/assets/images/gallery/Image-7.png',
          'src/assets/images/gallery/Image-4.png',
          'src/assets/images/gallery/Image-5.png',
          'src/assets/images/gallery/Image-6.png',
          'src/assets/images/gallery/Image-7.png',
          'src/assets/images/gallery/Image-4.png',
          'src/assets/images/gallery/Image-5.png',
          'src/assets/images/gallery/Image-6.png',
          'src/assets/images/gallery/Image-7.png',
        ],
      },
      {
        title: "Science Lab",
        description: "Our hands-on science lab allows students to conduct experiments and explore scientific concepts in a fun and interactive way.",
        infoItems: [
          'src/assets/images/gallery/Image-8.png',
          'src/assets/images/gallery/Image-9.png',
          'src/assets/images/gallery/Image-10.png',
          'src/assets/images/gallery/Image-11.png',
          'src/assets/images/gallery/Image-8.png',
          'src/assets/images/gallery/Image-9.png',
          'src/assets/images/gallery/Image-10.png',
          'src/assets/images/gallery/Image-11.png',
          'src/assets/images/gallery/Image-8.png',
          'src/assets/images/gallery/Image-9.png',
          'src/assets/images/gallery/Image-10.png',
          'src/assets/images/gallery/Image-11.png',
        ],
      },
      {
        title: "Computer Lab",
        description: "Equipped with age-appropriate technology, the computer lab enhances students' digital literacy and computational skills",
        infoItems: [
          'src/assets/images/gallery/Image-12.png',
          'src/assets/images/gallery/Image-13.png',
          'src/assets/images/gallery/Image-14.png',
          'src/assets/images/gallery/Image-15.png',
          'src/assets/images/gallery/Image-12.png',
          'src/assets/images/gallery/Image-13.png',
          'src/assets/images/gallery/Image-14.png',
          'src/assets/images/gallery/Image-15.png',
          'src/assets/images/gallery/Image-12.png',
          'src/assets/images/gallery/Image-13.png',
          'src/assets/images/gallery/Image-14.png',
          'src/assets/images/gallery/Image-15.png',
        ],
      },
      {
        title: "Garden and Nature Area",
        description: "Our garden and nature area offer an opportunity for children to connect with nature and learn about plants and the environment.",
        infoItems: [
          'src/assets/images/gallery/Image-16.png',
          'src/assets/images/gallery/Image-17.png',
          'src/assets/images/gallery/Image-18.png',
          'src/assets/images/gallery/Image-19.png',
          'src/assets/images/gallery/Image-16.png',
          'src/assets/images/gallery/Image-17.png',
          'src/assets/images/gallery/Image-18.png',
          'src/assets/images/gallery/Image-19.png',
          'src/assets/images/gallery/Image-16.png',
          'src/assets/images/gallery/Image-17.png',
          'src/assets/images/gallery/Image-18.png',
          'src/assets/images/gallery/Image-19.png',
        ],
      },
    ],
  },
  {
    title: 'Classrooms',
    items: [
      {
        title: "Classrooms",
        description: "Our well-equipped classrooms are designed to provide a nurturing and stimulating learning environment. Each classroom is thoughtfully arranged to inspire creativity, curiosity, and engagement.",
        infoItems: [
          'src/assets/images/gallery/Image.png',
          'src/assets/images/gallery/Image-1.png',
          'src/assets/images/gallery/Image-2.png',
          'src/assets/images/gallery/Image-3.png',
          'src/assets/images/gallery/Image.png',
          'src/assets/images/gallery/Image-1.png',
          'src/assets/images/gallery/Image-2.png',
          'src/assets/images/gallery/Image-3.png',
          'src/assets/images/gallery/Image.png',
          'src/assets/images/gallery/Image-1.png',
          'src/assets/images/gallery/Image-2.png',
          'src/assets/images/gallery/Image-3.png',
        ],
      },
    ],
  },
  {
    title: 'Library',
    items: [
      {
        title: "Library",
        description: "Our expansive library is a treasure trove of books, fostering a love for reading and supporting students' literacy development.",
        infoItems: [
          'src/assets/images/gallery/Image-4.png',
          'src/assets/images/gallery/Image-5.png',
          'src/assets/images/gallery/Image-6.png',
          'src/assets/images/gallery/Image-7.png',
          'src/assets/images/gallery/Image-4.png',
          'src/assets/images/gallery/Image-5.png',
          'src/assets/images/gallery/Image-6.png',
          'src/assets/images/gallery/Image-7.png',
          'src/assets/images/gallery/Image-4.png',
          'src/assets/images/gallery/Image-5.png',
          'src/assets/images/gallery/Image-6.png',
          'src/assets/images/gallery/Image-7.png',
        ],
      },
    ],
  },
  {
    title: 'Science Lab',
    items: [
      {
        title: "Science Lab",
        description: "Our hands-on science lab allows students to conduct experiments and explore scientific concepts in a fun and interactive way.",
        infoItems: [
          'src/assets/images/gallery/Image-8.png',
          'src/assets/images/gallery/Image-9.png',
          'src/assets/images/gallery/Image-10.png',
          'src/assets/images/gallery/Image-11.png',
          'src/assets/images/gallery/Image-8.png',
          'src/assets/images/gallery/Image-9.png',
          'src/assets/images/gallery/Image-10.png',
          'src/assets/images/gallery/Image-11.png',
          'src/assets/images/gallery/Image-8.png',
          'src/assets/images/gallery/Image-9.png',
          'src/assets/images/gallery/Image-10.png',
          'src/assets/images/gallery/Image-11.png',
        ],
      },
    ],
  },
  {
    title: 'Computer Lab',
    items: [
      {
        title: "Computer Lab",
        description: "Equipped with age-appropriate technology, the computer lab enhances students' digital literacy and computational skills",
        infoItems: [
          'src/assets/images/gallery/Image-12.png',
          'src/assets/images/gallery/Image-13.png',
          'src/assets/images/gallery/Image-14.png',
          'src/assets/images/gallery/Image-15.png',
          'src/assets/images/gallery/Image-12.png',
          'src/assets/images/gallery/Image-13.png',
          'src/assets/images/gallery/Image-14.png',
          'src/assets/images/gallery/Image-15.png',
          'src/assets/images/gallery/Image-12.png',
          'src/assets/images/gallery/Image-13.png',
          'src/assets/images/gallery/Image-14.png',
          'src/assets/images/gallery/Image-15.png',
        ],
      },
    ],
  },
  {
    title: 'Garden and Nature Area',
    items: [
      {
        title: "Garden and Nature Area",
        description: "Our garden and nature area offer an opportunity for children to connect with nature and learn about plants and the environment.",
        infoItems: [
          'src/assets/images/gallery/Image-16.png',
          'src/assets/images/gallery/Image-17.png',
          'src/assets/images/gallery/Image-18.png',
          'src/assets/images/gallery/Image-19.png',
          'src/assets/images/gallery/Image-16.png',
          'src/assets/images/gallery/Image-17.png',
          'src/assets/images/gallery/Image-18.png',
          'src/assets/images/gallery/Image-19.png',
          'src/assets/images/gallery/Image-16.png',
          'src/assets/images/gallery/Image-17.png',
          'src/assets/images/gallery/Image-18.png',
          'src/assets/images/gallery/Image-19.png',
        ],
      },
    ],
  },
]

export default galleryGroups